Quotes/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from upload import views




urlpatterns = [
    url(r'^$',views.home.as_view(),name='home'),
    url(r'^home/',include('upload.urls')),
    url(r'^admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.conf.urls import url
from . import views



app_name = 'upload'

urlpatterns = [
    #/home/
    url(r'^$',views.home.as_view(),name='home'),
    #/home/register
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    #home/login
    url(r'^login/$',views.LoginUser.as_view(),name='login'),

    url(r'^logout/$',views.logoutuser,name='logout'),




    #/home/712/

    url(r'^(?P<pk>[0-9]+)/$',views.detail.as_view(), name= 'detail'),

    #/home/add/

    url(r'^add/$',views.AuthorCreate.as_view(),name='author-add'),

    #home/update/6
    url(r'^update/(?P<pk>[0-9]+)/$',views.AuthorUpdate.as_view(),name='author-update'),
    #home/update/6
    url(r'^(?P<pk>[0-9]+)/delete$', views.AuthorDelete.as_view(), name='author-delete'),

    url(r'^quote/add/$',views.SayingCreate.as_view(),name='saying-add'),

    url(r'^edit/(?P<pk>[0-9]+)/$',views.SayingUpdate.as_view(),name='saying-edit'),



]

upload/models.py
from django.db import models
from django.urls import reverse

class Author(models.Model):
    author = models.CharField(max_length=100)
    author_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('upload:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.author

class Saying(models.Model):
    speaker = models.ForeignKey(Author,on_delete=models.CASCADE)
    category = models.CharField(max_length=50)
    content = models.TextField(max_length=1000)

    def get_absolute_url(self):
        return reverse('upload:detail',kwargs={'pk':self.speaker_id})


    def __str__(self):

        return self.category

upload/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:

        model = User
        fields=['first_name','username','email','password']

class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:

        model = User
        fields=['username','password']

upload/views.py
from django.views import generic
from .models import Author,Saying
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View
from .forms import UserForm,LoginForm
from django.contrib.auth.mixins import LoginRequiredMixin

class home(generic.ListView):
    template_name = 'upload/home.html'

    def get_queryset(self):
        return Author.objects.all()

class detail(generic.DetailView):
    model = Author
    template_name = 'upload/detail.html'

class AuthorCreate(LoginRequiredMixin,CreateView):
    login_url = "upload:login"
    model = Author
    fields = ['author','author_logo']

class AuthorUpdate(LoginRequiredMixin,UpdateView):
    login_url = "upload:login"
    model = Author
    fields = ['author','author_logo']

class AuthorDelete(LoginRequiredMixin,DeleteView):
    login_url = "upload:login"
    model = Author
    success_url = reverse_lazy('upload:home')

class SayingCreate(LoginRequiredMixin,CreateView):
    login_url = "upload:login"
    model = Saying
    fields = ['speaker','category','content']
class SayingUpdate(LoginRequiredMixin,UpdateView):
    login_url = "upload:login"
    model = Saying
    fields = ['category','content']


class UserFormView(View):
    form_class= UserForm
    template_name = 'upload/registration_form.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form= self.form_class(request.POST)

        if form.is_valid():
            user = form.save()

            username=form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)

            user.save()


            user = authenticate(username=username,password=password)

            if user is not None:



                if user.is_active:
                    login(request, user)
                    return redirect('upload:home')

        return render(request, self.template_name, {'form': form})


class LoginUser(View):
    template_name='upload/login_form.html'
    form_class= LoginForm

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username,password=password)

        if user is not None and user.is_active:
            login(request,user)
            return redirect('upload:home')

        return render(request, self.template_name, {'form': form})


def logoutuser(request):
        logout(request)

        return redirect('upload:login')

upload/templates/upload/author_form.html
{% extends 'upload/base.html' %}
{% block title %}Quotes | author {% endblock %}
{% block body %}
<section>

        <div class="login">
            <h1>Add author Here.</h1>
            <form id="log"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
        {% include 'upload/form-template.html' %}

        <button type="submit">Submit</button>




            </form>
            </div>




    </section>
     <footer>

        <p>bassam alamin quote site &copy;2018</p>


    </footer>
{% endblock %}

upload/templates/upload/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Quotes{% endblock %}</title>
    {% load staticfiles %}

    <link type="text/css" rel="stylesheet" href="{% static 'upload/style.css' %}"/>

</head>
<body>
    <header>
        <div class="container">
                <div id="brand">
                    <h1><a href="{% url 'upload:home' %}">Quotes</a></h1>
                </div>

            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'upload:author-add' %}">Add Author</a></li>
                        <li><a href="{% url 'upload:saying-add' %}">Add Saying</a></li>
                        <li><a href="{% url 'upload:logout' %}">Logout</a></li>
                    {% endif %}
                    {% if user.is_anonymous %}
                        <li><a href="{% url 'upload:login' %}">Login</a></li>
                        <li><a href="{% url 'upload:register' %}">Register</a></li>
                    {% endif %}



                </ul>

            </nav>

        </div>

    </header>
{% block body %}
{% endblock %}

</body>
</html>

upload/templates/upload/detail.html
{% extends 'upload/base.html' %}
{% block title %}Quotes | Details {% endblock %}
{% block body %}
 <section>
        <div class="image">

            <img src="{{ author.author_logo.url }}">
            <h1>{{ author.author }} &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {% if user.is_authenticated %}<a href="{% url 'upload:author-update' author.id %}">Edit Author</a>{% endif %}&nbsp;&nbsp;<a href="#">Delete Author</a></h1>
        </div>


        {% for saying in author.saying_set.all %}
            <div class="quotes">
                <p style="float:left;"><u><b>{{ saying.category }}</b></u></p>
                    {% if user.is_authenticated %}<p style="float:right;"><a href="{% url 'upload:saying-edit' saying.id %}">Edit Saying</a></p>{% endif %}
                    <br>

                    <p>{{ saying.content }}</p>
            </div>

        {% endfor %}



    </section>









<form action="{% url 'upload:author-delete' author.id %}" method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
    <footer>
        <p>bassam alamin quote site &copy;2018</p>


    </footer>
{% endblock %}

upload/templates/upload/form-template.html
{% for field in form %}
    <p>{{ field.label_tag }}</p>
    <div>{{ field }}</div>
    <br>

{% endfor %}

upload/templates/upload/home.html
{% extends 'upload/base.html' %}
{% block title %}Quotes | welcome {% endblock %}
{% block body %}

    {% load staticfiles %}

     <section id="slideshow">

        <div id="slide">
        </div>
    </section>
    <aside id="side">
        <div class ="container">
            <img src="{% static 'upload/images/javas.jpg' %}">

            <p>remember no one listens to a poor philosopher</p>

        </div>



    </aside>
    <section id="author">

<h5>Here is the list of the Authors</h5>
<ul>
    {% for author in object_list %}
        <li><a href="{% url 'upload:detail' author.id %}">{{ author.author }}</a></li>


    {% endfor %}

</ul>
    </section>

    <footer>

        <p>bassam alamin quote site &copy;2018</p>


    </footer>




{% endblock %}

upload/templates/upload/login_form.html
{% extends 'upload/base.html' %}
{% block title %}Quotes | Login {% endblock %}
{% block body %}


    <section>

        <div class="login">
            <h1>Log in here.</h1>
            <form id="log"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
        {% include 'upload/form-template.html' %}

        <button type="submit">login</button>




            </form>
            </div>




    </section>
     <footer>

        <p>bassam alamin quote site &copy;2018</p>


    </footer>

{% endblock %}

upload/templates/upload/registration_form.html
{% extends 'upload/base.html' %}
{% block title %}Quotes | Register {% endblock %}
{% block body %}
<section>

        <div class="login">
            <h1>Register here.</h1>
            <form id="log"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
        {% include 'upload/form-template.html' %}

        <button type="submit">Register</button>




            </form>
            </div>




    </section>
     <footer>

        <p>bassam alamin quote site &copy;2018</p>


    </footer>



</form>
{% endblock %}

upload/templates/upload/saying-template.html
{% for field in form %}
    <label>{{ field.label_tag }}</label>
    <div>{{ field }}</div>
    <br>

{% endfor %}

upload/templates/upload/saying_form.html
{% extends 'upload/base.html' %}
{% block title %}Quotes | Saying {% endblock %}
{% block body %}
<section>

        <div class="login">
            <h1>Add saying here.</h1>
            <form id="log"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
        {% include 'upload/form-template.html' %}

        <button type="submit">Submit</button>




            </form>
            </div>




    </section>
     <footer>

        <p>bassam alamin quote site &copy;2018</p>


    </footer>
{% endblock %}